on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: Run pull
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/DevTanam123
        chmod 600 ~/.ssh/DevTanam123
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Debug SSH connection
      run: |
        ssh -i ~/.ssh/DevTanam123 ${USERNAME}@${HOST} "echo Connected successfully!"

    - name: Connect and pull
      run: |
        ssh -i ~/.ssh/DevTanam123 ${USERNAME}@${HOST} "cd ${WORK_DIR} && git checkout ${MAIN_BRANCH} && git pull"
    - name: cleanup
      run: rm -rf ~/.ssh
